[package]
name = "rust_cpu_pid"
version = "0.1.0"
authors = ["Zain Ansari <zainussami@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
psutil = "3.1.0"